const data = {
    products: [
      {
        name: 'Samsung Galaxy',
        slug: 'Galaxy A-73',
        category: 'Phone',
        image:'public/images/IMG-20220803-WA0054.jpg' ,
        price: 52000,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'New phone',
        
      },
      {
        name: 'Nissan Juke',
        slug: 'Juke',
        category: 'Car',
        image: 'public/images/IMG-20220806-WA0004.jpg',
        price: 1500000,
        countInStock: 1,
        brand: 'Nissan',
        rating: 4.0,
        numReviews: 10,
        description: 'Accident free',
        
      },
      {
        name: 'Prado J-150',
        slug: 'Toyota Land cruiser',
        category: 'CAR',
        image: 'public/images/IMG-20220806-WA0005.jpg',
        price: 3500000,
        countInStock: 1,
        brand: 'Land Cruiser',
        rating: 4.5,
        numReviews: 14,
        description: 'Accident free',
      },
      {
        name: 'Toyota LAND CRUISER',
        slug: 'V8',
        category: 'SUV',
        image: 'public/images/IMG-20220806-WA0011.jpg',
        price: 5000000,
        countInStock: 5,
        brand: 'TOYOTA',
        rating: 4.5,
        numReviews: 10,
        description: 'BIG MACHINE',
      },
      {
        name: 'puma sleek ',
        slug: 'low puma',
        category: 'Shoe',
        image:'public/images/IMG-20220806-WA0047.jpg' ,
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shoe',
      },
      {
        name: 'German Sufurias',
        slug: 'German Kitchenware',
        category: 'Kitcenware',
        image:'public/images/IMG-20220806-WA0033.jpg' ,
        price: 12000,
        countInStock: 10,
        brand: 'Bosch',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality pots',
      },
      {
        name: 'LED bulb',
        slug: 'LED',
        category: 'household',
        image:'public/images/IMG-20220806-WA0034.jpg' ,
        price: 200,
        countInStock: 10,
        brand: 'Light',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality LED bulb',
      },
      {
        name: 'HP LAPTOP',
        slug: 'HP',
        category: 'Electronic',
        image:'public/images/IMG-20220814-WA0073.jpg' ,
        price: 22000,
        countInStock: 9,
        brand: 'hp',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality laptop',
      },
      {
        name: 'German pot',
        slug: 'white German pots',
        category: 'kitchenware',
        image:'public/images/IMG-20220806-WA0036.jpg' ,
        price: 12000,
        countInStock: 10,
        brand: 'bosch',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality pots',
      },
      {
        name: 'Puma sneakers',
        slug: 'Puma',
        category: 'Shoes',
        image:'public/images/IMG-20220806-WA0037.jpg' ,
        price: 2000,
        countInStock: 10,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality sneaker',
      },
      {
        name: 'Nike Slim shirt',
        slug: 'nike-slim-shirt',
        category: 'Shirts',
        image:'' ,
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: 'Nike Slim shirt',
        slug: 'nike-slim-shirt',
        category: 'Shirts',
        image:'' ,
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
    ],
  };
  export default data;